//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OP_Macro.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112")]
        public uint autoclickerHotkeyProperty {
            get {
                return ((uint)(this["autoclickerHotkeyProperty"]));
            }
            set {
                this["autoclickerHotkeyProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115")]
        public uint textHotkeyProperty {
            get {
                return ((uint)(this["textHotkeyProperty"]));
            }
            set {
                this["textHotkeyProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("116")]
        public uint recordHotkeyProperty {
            get {
                return ((uint)(this["recordHotkeyProperty"]));
            }
            set {
                this["recordHotkeyProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("117")]
        public uint replayHotkeyProperty {
            get {
                return ((uint)(this["replayHotkeyProperty"]));
            }
            set {
                this["replayHotkeyProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("113")]
        public uint firstCoordHotkeyProperty {
            get {
                return ((uint)(this["firstCoordHotkeyProperty"]));
            }
            set {
                this["firstCoordHotkeyProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("114")]
        public uint secondCoordHotkeyProperty {
            get {
                return ((uint)(this["secondCoordHotkeyProperty"]));
            }
            set {
                this["secondCoordHotkeyProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public uint teleportHotkeyProperty {
            get {
                return ((uint)(this["teleportHotkeyProperty"]));
            }
            set {
                this["teleportHotkeyProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("119")]
        public uint richText1HotkeyProperty {
            get {
                return ((uint)(this["richText1HotkeyProperty"]));
            }
            set {
                this["richText1HotkeyProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public uint richText2HotkeyProperty {
            get {
                return ((uint)(this["richText2HotkeyProperty"]));
            }
            set {
                this["richText2HotkeyProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("121")]
        public uint richText3HotkeyProperty {
            get {
                return ((uint)(this["richText3HotkeyProperty"]));
            }
            set {
                this["richText3HotkeyProperty"] = value;
            }
        }
    }
}
